# Übungsblatt 4

## Aufgabe 9

In [6]:
import sympy as sp
import numpy as np

In [86]:
data = [
    [1, 5, 4, 1, 6],
    [5, 11, 8, 2, 13],
    [3, 13, 11, 2, 15],
    [-1, 1, 1, 1, 1]
]
A = sp.Matrix(A)

In [91]:
A.rref()

(Matrix([
 [1, 0, -13/5, 18/5],
 [0, 1,  -1/5,  1/5]]),
 (0, 1))

In [92]:
np.linalg.matrix_rank(np.array(B).astype(np.float64))

/tmp/ipykernel_3041/589198011.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.linalg.matrix_rank(np.array(B).astype(np.float64))


ValueError: could not broadcast input array from shape (2,4) into shape (2,)

## Aufgabe 10

a)

In [73]:
A = []
for i in range(1, 3):
    tmp = []
    for j in range(1, 11):
        tmp.append(i if i == 1 else i**2)
    A.append(tmp)
sp.Matrix(A)

Matrix([
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
[4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

b)

In [76]:
B = []
for i in range(1, 7):
    tmp = []
    for j in range(1, 7):
        tmp.append(0 if i == j else i + j if i < j else i - j)
    B.append(tmp)
sp.Matrix(B)

Matrix([
[0, 3, 4, 5, 6,  7],
[1, 0, 5, 6, 7,  8],
[2, 1, 0, 7, 8,  9],
[3, 2, 1, 0, 9, 10],
[4, 3, 2, 1, 0, 11],
[5, 4, 3, 2, 1,  0]])

In [77]:
C = []
for i in range(1, 6):
    tmp = []
    for j in range(1, 6):
        tmp.append(0 if i + j < 6 else 1 if i + j == 6 else 2)
    C.append(tmp)
sp.Matrix(C)

Matrix([
[0, 0, 0, 0, 1],
[0, 0, 0, 1, 2],
[0, 0, 1, 2, 2],
[0, 1, 2, 2, 2],
[1, 2, 2, 2, 2]])

## Aufgabe 10

In [79]:
## a
A = np.array([[1, 2, -3, 4], [0, -5, 1, -1]])
B = np.array([[3, -5, 6, -1], [2, 0, -2, 3]])
A + B

array([[ 4, -3,  3,  3],
       [ 2, -5, -1,  2]])

In [80]:
-3 * np.array([[1, 2, -3], [4, -5, 6]])

array([[ -3,  -6,   9],
       [-12,  15, -18]])

In [82]:
C = np.array([[2, -1], [1, 0], [-3, 4]])
D = np.array([[1, -2, -5], [3, 4, 0]])

np.dot(C, D)

array([[ -1,  -8, -10],
       [  1,  -2,  -5],
       [  9,  22,  15]])

In [83]:
np.linalg.matrix_power(np.array([[1, 2], [0, 1]]), 10)

array([[ 1, 20],
       [ 0,  1]])